<a href="https://colab.research.google.com/github/Davisitop/ejercicio1/blob/main/PARTE_TALLER.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Practica Modulo 1**
## Nombre:Juan David Villacis
## Fecha:21 de Abril del 2026

# 1.1 Listas y Comprehensions

In [ ]:

# Creación y Slicing
edades = [18, 21, 24, 27, 30]
mixta_modificada = [5, 'servidor', 9.99, False]

print(edades[0])       # Primer elemento: 18
print(edades[-1])      # Último elemento: 30
print(edades[1:4])     # Slicing [21, 24, 27]
print(edades[::-1])    # Lista invertida

# Métodos
edades.append(33)      # Agrega al final
edades.insert(1, 19)   # Inserta el 19 en la posición 1
edades.pop()           # Extrae el último (33)
print("Lista actual:", edades)

# List Comprehensions
cubos = [x**3 for x in range(1, 6)]
impares = [x for x in range(1, 21) if x % 2 != 0]
print("Cubos:", cubos)
print("Impares:", impares)

18
30
[21, 24, 27]
[30, 27, 24, 21, 18]
Lista actual: [18, 19, 21, 24, 27, 30]
Cubos: [1, 8, 27, 64, 125]
Impares: [1, 3, 5, 7, 9, 11, 13, 15, 17, 19]


# 1.2 y 1.3 Tuplas y Diccionarios

In [ ]:
# Tuplas (Inmutables)
sensor_dht = (25.4, 60.2) # Temperatura y humedad
temp, hum = sensor_dht    # Desempaquetado
print(f"Temperatura: {temp}, Humedad: {hum}")

# Diccionarios (Clave-Valor)
proyecto = {
    'nombre': 'Sistema Automático',
    'version': 1.2,
    'modulos': ['Sensor', 'Actuador', 'Web'],
    'en_produccion': True
}

print(proyecto['nombre'])
print(proyecto.get('autor', 'No especificado')) # get seguro

proyecto['version'] = 2.0  # Modificación
proyecto['framework'] = 'Angular' # Nueva clave

# Dict Comprehension
dobles_dict = {x: x*2 for x in range(1, 5)}
print("Diccionario dobles:", dobles_dict)

Temperatura: 25.4, Humedad: 60.2
Sistema Automático
No especificado
Diccionario dobles: {1: 2, 2: 4, 3: 6, 4: 8}


# 1.4 Funciones

In [ ]:
# Función con parámetros por defecto y retorno múltiple
def analizar_datos(lista, factor=2):
    minimo = min(lista) * factor
    maximo = max(lista) * factor
    return minimo, maximo

val_min, val_max = analizar_datos([5, 10, 15, 20])
print(f"Mínimo ajustado: {val_min}, Máximo ajustado: {val_max}")

# Lambda, map y filter
numeros = [2, 5, 8, 11, 14]
triples = list(map(lambda x: x * 3, numeros))
mayores_a_10 = list(filter(lambda x: x > 10, numeros))
print("Triples:", triples)
print("Filtrados:", mayores_a_10)

Mínimo ajustado: 10, Máximo ajustado: 40
Triples: [6, 15, 24, 33, 42]
Filtrados: [11, 14]


## MÓDULO 2: NumPy - Creación de Arrays
# 2.2 y 2.3 Creación y Atributos

In [ ]:
import numpy as np

# Desde listas
vector = np.array([100, 200, 300, 400])
matriz = np.array([[10, 20], [30, 40], [50, 60]])
flotantes = np.array([5, 10, 15], dtype=np.float32)

# Funciones especializadas
ceros_mod = np.zeros((2, 4))
unos_mod = np.ones((3, 2))
identidad_mod = np.eye(3)

# rangos y espacios
rango_np = np.arange(10, 50, 10) # 10, 20, 30, 40
espaciado = np.linspace(0, 10, 5) # 5 puntos entre 0 y 10

# Aleatorios (Cambiando la semilla para variar)
np.random.seed(15)
enteros_aleatorios = np.random.randint(1, 100, size=(3, 3))

print("Shape de la matriz:", matriz.shape)
print("Dimensiones:", matriz.ndim)
print("Tipo de dato:", flotantes.dtype)
print("Matriz aleatoria:\n", enteros_aleatorios)

Shape de la matriz: (3, 2)
Dimensiones: 2
Tipo de dato: float32
Matriz aleatoria:
 [[73 13  6]
 [ 1 29 28]
 [72 76 86]]


# 3.1 y 3.2 Indexing y Slicing

In [ ]:
matriz_base = np.array([[15, 25, 35],
                        [45, 55, 65],
                        [75, 85, 95]])

# Acceso
print("Elemento central:", matriz_base[1, 1]) # 55
print("Última fila:", matriz_base[-1, :])

# Slicing (Recuerda que es una VISTA)
sub_matriz = matriz_base[0:2, 1:3]
print("Sub-matriz:\n", sub_matriz)

# Copia explícita
copia_segura = matriz_base[0, :].copy()
copia_segura[0] = 999
print("Copia modificada:", copia_segura)
print("Original intacta:", matriz_base[0, :])

Elemento central: 55
Última fila: [75 85 95]
Sub-matriz:
 [[25 35]
 [55 65]]
Copia modificada: [999  25  35]
Original intacta: [15 25 35]


# 3.3, 3.4 y 3.5 Máscaras, Fancy Indexing y Reshape

In [ ]:
datos_crudos = np.array([8, 15, 2, 22, 5, 18, 10])

# Máscara booleana
mascara = datos_crudos >= 10
print("Valores >= 10:", datos_crudos[mascara])

# np.where (Condicional)
# Si es mayor a 10 se queda igual, si no, se vuelve 0
limpios = np.where(datos_crudos > 10, datos_crudos, 0)
print("Datos limpios:", limpios)

# Fancy Indexing
matriz_fi = np.arange(10, 19).reshape(3, 3)
filas_seleccionadas = matriz_fi[[2, 0, 2]] # Elige filas arbitrarias
print("Fancy Indexing:\n", filas_seleccionadas)

# Reshape
vector_12 = np.arange(12)
matriz_3x4 = vector_12.reshape(3, 4)
tensor_auto = vector_12.reshape(2, 2, -1) # Calcula el -1 automáticamente
print("Tensor 3D shape:", tensor_auto.shape)

Valores >= 10: [15 22 18 10]
Datos limpios: [ 0 15  0 22  0 18  0]
Fancy Indexing:
 [[16 17 18]
 [10 11 12]
 [16 17 18]]
Tensor 3D shape: (2, 2, 3)


# 4.1 a 4.4 Operaciones Elemento a Elemento, Broadcasting y Reducciones

In [ ]:
v1 = np.array([2, 4, 6, 8])
v2 = np.array([1, 2, 3, 4])

# Aritmética
print("Suma:", v1 + v2)
print("Potencia:", v1 ** 2)

# Broadcasting (Matriz + Vector)
matriz_datos = np.ones((3, 4))
vector_suma = np.array([10, 20, 30, 40])
print("Broadcasting:\n", matriz_datos + vector_suma)

# Funciones Universales (ufuncs)
valores_neg = np.array([-3.5, 0.0, 4.2, -1.1])
print("Valor absoluto:", np.abs(valores_neg))
print("Redondeo arriba:", np.ceil(valores_neg))

# Reducciones (Estadística)
calificaciones = np.array([[80, 90, 70],
                           [85, 95, 75],
                           [60, 65, 80]])

print("Promedio general:", calificaciones.mean())
print("Máximo por columna (Materia):", calificaciones.max(axis=0))
print("Suma por fila (Estudiante):", calificaciones.sum(axis=1))

Suma: [ 3  6  9 12]
Potencia: [ 4 16 36 64]
Broadcasting:
 [[11. 21. 31. 41.]
 [11. 21. 31. 41.]
 [11. 21. 31. 41.]]
Valor absoluto: [3.5 0.  4.2 1.1]
Redondeo arriba: [-3.  0.  5. -1.]
Promedio general: 77.77777777777777
Máximo por columna (Materia): [85 95 80]
Suma por fila (Estudiante): [240 255 205]


# 4.5 y 4.6 Concatenación y Ordenamiento

In [ ]:
import numpy as np

m_a = np.array([[10, 20], [30, 40]])
m_b = np.array([[50, 60], [70, 80]])

# Concatenar
apilado_v = np.vstack([m_a, m_b])
apilado_h = np.hstack([m_a, m_b])
print("Stack vertical:\n", apilado_v)

# Ordenamiento
aleatorios = np.array([45, 12, 89, 33, 7])
aleatorios_ordenados = np.sort(aleatorios)

# Argsort (Mantiene relación con otros arrays)
ids_productos = np.array(['P1', 'P2', 'P3', 'P4'])
precios = np.array([99.9, 15.5, 45.0, 10.0])

orden_precios = np.argsort(precios)
print("Productos más baratos a más caros:", ids_productos[orden_precios])

Stack vertical:
 [[10 20]
 [30 40]
 [50 60]
 [70 80]]
Productos más baratos a más caros: ['P4' 'P2' 'P3' 'P1']
