<a href="https://colab.research.google.com/github/Davisitop/ejercicio1/blob/main/PARTE_PARTICA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Practica
### Nombre:David Villacis
### fecha:21 de Abril del 2026

# PRACTICA 1

---



In [ ]:
# --- Ejercicio 1 ---
# Múltiplos de 7 entre 1 y 100 usando comprehension
multiplos_de_7 = [x for x in range(1, 101) if x % 7 == 0]
print("Ej 1 - Múltiplos de 7:", multiplos_de_7)

# --- Ejercicio 2 --- [cite: 266]
datos = {'a':10, 'b':25, 'c':7, 'd':18}

# a) Claves con valor mayor a 12
claves_mayores = [clave for clave, valor in datos.items() if valor > 12]
print("Ej 2a - Claves mayores a 12:", claves_mayores)

# b) Nuevo diccionario con los valores al cuadrado [cite: 268]
nuevo_diccionario = {clave: datos[clave]**2 for clave in claves_mayores}
print("Ej 2b - Nuevo diccionario:", nuevo_diccionario)

# --- Ejercicio 3 ---
def resumen(lista):
    # Lo hago paso a paso para que sea más claro
    longitud = len(lista)
    suma_total = sum(lista)
    promedio = suma_total / longitud
    val_minimo = min(lista)
    val_maximo = max(lista)

    # Armo el diccionario de respuesta
    resultado = {
        'longitud': longitud,
        'suma': suma_total,
        'promedio': promedio,
        'minimo': val_minimo,
        'maximo': val_maximo
    }
    return resultado

mi_lista = [5, 10, 15, 20]
print("Ej 3 - Resumen:", resumen(mi_lista))

# --- Ejercicio 4 ---
def potencia(x, exponente=2):
    return x ** exponente

lista_numeros = [1, 2, 3, 4, 5]
# Uso lambda para poder pasarle el 3 como exponente a la función
resultado_map = list(map(lambda num: potencia(num, 3), lista_numeros))
print("Ej 4 - Cubos con map:", resultado_map)

Ej 1 - Múltiplos de 7: [7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98]
Ej 2a - Claves mayores a 12: ['b', 'd']
Ej 2b - Nuevo diccionario: {'b': 625, 'd': 324}
Ej 3 - Resumen: {'longitud': 4, 'suma': 50, 'promedio': 12.5, 'minimo': 5, 'maximo': 20}
Ej 4 - Cubos con map: [1, 8, 27, 64, 125]


# PRACTICA 2

---



In [ ]:
import numpy as np

# --- Ejercicio 1 ---
# a) Vector del 1 al 20
vector_20 = np.arange(1, 21)
print("Ej 1a - Vector:", vector_20.shape, vector_20.dtype, vector_20.ndim)

# b) Matriz de ceros 5x3
matriz_ceros = np.zeros((5, 3))
print("Ej 1b - Ceros:", matriz_ceros.shape, matriz_ceros.dtype, matriz_ceros.ndim)

# c) 10 puntos con linspace
puntos = np.linspace(-1, 1, 10)
print("Ej 1c - Puntos linspace:", puntos.shape, puntos.dtype, puntos.ndim)

# --- Ejercicio 2 ---
np.random.seed(99) # Para que siempre salgan los mismos números aleatorios
matriz_aleatoria = np.random.randint(0, 50, size=(4, 4))
print("\nEj 2 - Matriz aleatoria:\n", matriz_aleatoria)
print("Shape:", matriz_aleatoria.shape)
print("Dtype:", matriz_aleatoria.dtype)
print("Bytes ocupados:", matriz_aleatoria.nbytes)
print("Elemento [2,3] (Fila 3, Columna 4):", matriz_aleatoria[2, 3])

# --- Ejercicio 3 ---
arr_enteros = np.array([1, 2, 3])
arr_decimales = np.array([1.0, 2.0, 3.0])
# El primero es int (entero) y el segundo se vuelve float (decimal) automáticamente
print("\nEj 3 - Dtype enteros:", arr_enteros.dtype)
print("Ej 3 - Dtype decimales:", arr_decimales.dtype)

# --- Ejercicio 4 ---
identidad = np.eye(5)
suma_diagonal = np.trace(identidad)
print("\nEj 4 - Suma de la diagonal:", suma_diagonal)

Ej 1a - Vector: (20,) int64 1
Ej 1b - Ceros: (5, 3) float64 2
Ej 1c - Puntos linspace: (10,) float64 1

Ej 2 - Matriz aleatoria:
 [[ 1 35 40  9]
 [40 18  4  5]
 [ 1 23 35 49]
 [ 1 48 29 38]]
Shape: (4, 4)
Dtype: int64
Bytes ocupados: 128
Elemento [2,3] (Fila 3, Columna 4): 49

Ej 3 - Dtype enteros: int64
Ej 3 - Dtype decimales: float64

Ej 4 - Suma de la diagonal: 5.0


# PRACTICA 3

---



In [ ]:
import numpy as np

# --- Ejercicio 1 ---
A = np.arange(1, 26).reshape(5, 5)

# a) 3 últimas filas (-3 al final) y 3 primeras columnas (0 al 3)
sub_matriz = A[-3:, 0:3]
print("Ej 1a - Sub-matriz:\n", sub_matriz)

# b) Segunda columna completa
segunda_columna = A[:, 1] # El índice 1 es la segunda columna
print("Ej 1b - Segunda columna:", segunda_columna)

# c) Elementos de las esquinas
# Extraigo una por una para no complicarme
esq_sup_izq = A[0, 0]
esq_sup_der = A[0, -1]
esq_inf_izq = A[-1, 0]
esq_inf_der = A[-1, -1]
esquinas = np.array([esq_sup_izq, esq_sup_der, esq_inf_izq, esq_inf_der])
print("Ej 1c - Esquinas:", esquinas)

# --- Ejercicio 2 ---
# a) Máscara booleana
mascara = A > 12

# b) Reemplazar en una copia
copia_A = A.copy()
copia_A[mascara] = -1
print("\nEj 2b - Copia con reemplazo:\n", copia_A)

# c) np.where para pares e impares
# Si el residuo de % 2 es distinto de 0 (impar), pongo 0, sino dejo A
matriz_pares = np.where(A % 2 != 0, 0, A)
print("Ej 2c - Solo pares:\n", matriz_pares)

# --- Ejercicio 3 ---
v24 = np.arange(24)
matriz_6x4 = v24.reshape(6, 4)
tensor_2x3x4 = v24.reshape(2, 3, 4)
vector_fila = v24.reshape(1, 24)

# --- Ejercicio 4 ---
original = np.array([10, 20, 30, 40])
vista_corte = original[1:3] # Hago un slice
vista_corte[0] = 999        # Modifico la vista
# Demostración de que el original sí se afectó
print("\nEj 4 - Array original modificado por la vista:", original)

Ej 1a - Sub-matriz:
 [[11 12 13]
 [16 17 18]
 [21 22 23]]
Ej 1b - Segunda columna: [ 2  7 12 17 22]
Ej 1c - Esquinas: [ 1  5 21 25]

Ej 2b - Copia con reemplazo:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]]
Ej 2c - Solo pares:
 [[ 0  2  0  4  0]
 [ 6  0  8  0 10]
 [ 0 12  0 14  0]
 [16  0 18  0 20]
 [ 0 22  0 24  0]]

Ej 4 - Array original modificado por la vista: [ 10 999  30  40]


# Módulo 4: Operaciones Numéricas y Manejo de Datos

---



In [ ]:
import numpy as np

# --- Ejercicio 1 ---
np.random.seed(7)
mat_5x4 = np.random.randint(1, 100, (5, 4))

# a) Estadísticas por columna (axis=0)
print("Ej 1a - Media por columna:", mat_5x4.mean(axis=0))
print("Ej 1a - Max por columna:", mat_5x4.max(axis=0))
print("Ej 1a - Min por columna:", mat_5x4.min(axis=0))

# b) Suma acumulada fila 1
fila_1 = mat_5x4[0, :]
print("\nEj 1b - Suma acumulada de fila 1:", np.cumsum(fila_1))

# c) Normalizar
min_cols = mat_5x4.min(axis=0)
max_cols = mat_5x4.max(axis=0)
# Aplico la fórmula que nos dieron usando broadcasting
mat_normalizada = (mat_5x4 - min_cols) / (max_cols - min_cols)
print("\nEj 1c - Matriz normalizada:\n", mat_normalizada.round(2))

# --- Ejercicio 2 ---
# a) Crear vectores
v_fila = np.array([1, 2, 3, 4])
v_col = np.array([[10], [20], [30]])

# b) Suma y explicación
resultado_suma = v_fila + v_col
print("\nEj 2 - Suma Broadcasting:\n", resultado_suma)
# El shape es 3x4 porque la fila de 4 se duplica hacia abajo 3 veces,
# y la columna de 3 se duplica hacia la derecha 4 veces para poder sumarse.

# --- Ejercicio 3 ---
nombres = np.array(['Carlos', 'Ana', 'Diana', 'Pedro', 'Eva', 'Luis'])
notas = np.array([75, 92, 88, 61, 95, 78])

promedio = notas.mean()
mascara_notas = notas > promedio

# a) Cuántos pasaron el promedio (True vale 1 al sumar)
cantidad_estudiantes = mascara_notas.sum()
print("\nEj 3a - Cantidad sobre el promedio:", cantidad_estudiantes)

# b) Mostrar nombres aplicando la máscara
print("Ej 3b - Estudiantes destacados:", nombres[mascara_notas])

# --- Ejercicio 4 ---
matriz_uno = np.ones((3, 4))
matriz_dos = np.zeros((3, 4))

apilado_vertical = np.vstack([matriz_uno, matriz_dos])
apilado_horizontal = np.hstack([matriz_uno, matriz_dos])

# Dividir el vertical (que ahora tiene 6 filas) en 3 partes
partes_divididas = np.vsplit(apilado_vertical, 3)
print("\nEj 4 - Tamaño de la primera partición:", partes_divididas[0].shape)

Ej 1a - Media por columna: [51.8 51.4 41.8 60.2]
Ej 1a - Max por columna: [84 91 93 90]
Ej 1a - Min por columna: [15 24  8 40]

Ej 1b - Suma acumulada de fila 1: [ 48 117 143 211]

Ej 1c - Matriz normalizada:
 [[0.48 0.67 0.21 0.56]
 [1.   0.   1.   0.36]
 [0.   0.   0.76 1.  ]
 [0.41 1.   0.01 0.  ]
 [0.78 0.37 0.   0.1 ]]

Ej 2 - Suma Broadcasting:
 [[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]

Ej 3a - Cantidad sobre el promedio: 3
Ej 3b - Estudiantes destacados: ['Ana' 'Diana' 'Eva']

Ej 4 - Tamaño de la primera partición: (2, 4)
